---
# tasks file for apach
- name: Install apache on ubuntu
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debain"
- name: Install apache on redhat
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "Redhat"
  notify:
  - Restart httpd
